
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lyza
 */
public class Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyImage1 = new fancyui.FancyImage();
        fancyButton10 = new fancyui.FancyButton();
        fancyButton11 = new fancyui.FancyButton();
        fancyButton12 = new fancyui.FancyButton();
        fancyButton13 = new fancyui.FancyButton();
        fancyButton14 = new fancyui.FancyButton();
        fancyLabel2 = new fancyui.FancyLabel();
        LogOut = new fancyui.FancyButton();
        fancyPanel4 = new fancyui.FancyPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fancyImage7 = new fancyui.FancyImage();
        fancyPanel7 = new fancyui.FancyPanel();
        fancyPanel16 = new fancyui.FancyPanel();
        fancyLabel14 = new fancyui.FancyLabel();
        fancyLabel4 = new fancyui.FancyLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fancyLabel6 = new fancyui.FancyLabel();
        jSeparator4 = new javax.swing.JSeparator();
        fancyLabel9 = new fancyui.FancyLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        fancyPanel22 = new fancyui.FancyPanel();
        fancyPanel23 = new fancyui.FancyPanel();
        fancyLabel22 = new fancyui.FancyLabel();
        fancyLabel18 = new fancyui.FancyLabel();
        fancyButton4 = new fancyui.FancyButton();
        fancyPanel24 = new fancyui.FancyPanel();
        fancyPanel25 = new fancyui.FancyPanel();
        fancyLabel19 = new fancyui.FancyLabel();
        fancyButton2 = new fancyui.FancyButton();
        fancyPanel15 = new fancyui.FancyPanel();
        fancyPanel17 = new fancyui.FancyPanel();
        fancyLabel15 = new fancyui.FancyLabel();
        fancyLabel3 = new fancyui.FancyLabel();
        jSeparator2 = new javax.swing.JSeparator();
        fancyLabel7 = new fancyui.FancyLabel();
        jSeparator5 = new javax.swing.JSeparator();
        fancyLabel10 = new fancyui.FancyLabel();
        fancyPanel18 = new fancyui.FancyPanel();
        fancyPanel19 = new fancyui.FancyPanel();
        fancyLabel16 = new fancyui.FancyLabel();
        fancyLabel5 = new fancyui.FancyLabel();
        jSeparator3 = new javax.swing.JSeparator();
        fancyLabel8 = new fancyui.FancyLabel();
        jSeparator6 = new javax.swing.JSeparator();
        fancyLabel11 = new fancyui.FancyLabel();
        fancyPanel28 = new fancyui.FancyPanel();
        fancyPanel29 = new fancyui.FancyPanel();
        fancyLabel21 = new fancyui.FancyLabel();
        fancyButton3 = new fancyui.FancyButton();
        fancyPanel26 = new fancyui.FancyPanel();
        fancyPanel27 = new fancyui.FancyPanel();
        fancyButton5 = new fancyui.FancyButton();
        fancyLabel20 = new fancyui.FancyLabel();
        fancyLabel17 = new fancyui.FancyLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fancyPanel1.setBorderColor(new java.awt.Color(228, 212, 238));
        fancyPanel1.setBorderEnabled(true);
        fancyPanel1.setBottomLeftRadius(0);
        fancyPanel1.setBottomRightRadius(0);
        fancyPanel1.setCornerRadius(0);
        fancyPanel1.setGradientEnd(new java.awt.Color(241, 223, 250));
        fancyPanel1.setGradientStart(new java.awt.Color(186, 130, 213));
        fancyPanel1.setSolidBackgroundColor(new java.awt.Color(229, 216, 236));
        fancyPanel1.setSolidBackgroundEnabled(true);

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/774148120_1731905104754691_9160798377654078668_n.png"))); // NOI18N
        fancyImage1.setScaleType(fancyui.FancyImage.ScaleType.FIT);

        fancyButton10.setText("Home");
        fancyButton10.setBorderEnabled(false);
        fancyButton10.setCornerRadius(13);
        fancyButton10.setHoverBackground(new java.awt.Color(145, 92, 232));

        fancyButton11.setText("Manage Users");
        fancyButton11.setBorderEnabled(false);
        fancyButton11.setCornerRadius(13);
        fancyButton11.setHoverBackground(new java.awt.Color(145, 92, 232));
        fancyButton11.addActionListener(this::fancyButton11ActionPerformed);

        fancyButton12.setText("Mange Core");
        fancyButton12.setBorderEnabled(false);
        fancyButton12.setCornerRadius(13);
        fancyButton12.setHoverBackground(new java.awt.Color(145, 92, 232));
        fancyButton12.addActionListener(this::fancyButton12ActionPerformed);

        fancyButton13.setText("View Report");
        fancyButton13.setBorderEnabled(false);
        fancyButton13.setCornerRadius(13);
        fancyButton13.setHoverBackground(new java.awt.Color(145, 92, 232));
        fancyButton13.addActionListener(this::fancyButton13ActionPerformed);

        fancyButton14.setText("Moderate Content");
        fancyButton14.setBorderEnabled(false);
        fancyButton14.setCornerRadius(13);
        fancyButton14.setHoverBackground(new java.awt.Color(145, 92, 232));

        fancyLabel2.setForeground(new java.awt.Color(202, 143, 232));
        fancyLabel2.setText("LUMINEX");
        fancyLabel2.setFont(new java.awt.Font("Super Bouncer", 0, 24)); // NOI18N

        LogOut.setText("Logout");
        LogOut.setBorderEnabled(false);
        LogOut.setCornerRadius(10);
        LogOut.setHoverBackground(new java.awt.Color(145, 92, 232));
        LogOut.addActionListener(this::LogOutActionPerformed);

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fancyButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(fancyButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(fancyButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jPanel1.add(fancyPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 710));

        fancyPanel4.setBorderColor(new java.awt.Color(241, 241, 241));
        fancyPanel4.setBorderEnabled(true);
        fancyPanel4.setCornerRadius(0);
        fancyPanel4.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel4.setSolidBackgroundEnabled(true);

        jLabel16.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel16.setText("Admin");

        jLabel22.setFont(new java.awt.Font("Winter Poppins", 0, 18)); // NOI18N
        jLabel22.setText("LUMINEX Quiz System");

        fancyImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-test-account-24.png"))); // NOI18N

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 519, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(fancyImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(fancyPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 730, 40));

        fancyPanel7.setGradientEnabled(false);
        fancyPanel7.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel7.setSolidBackgroundEnabled(true);

        fancyPanel16.setBorderEnabled(true);
        fancyPanel16.setGradientEnabled(false);
        fancyPanel16.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel16.setSolidBackgroundEnabled(true);

        fancyLabel14.setText("Total Users");
        fancyLabel14.setFont(new java.awt.Font("Magesta", 0, 24)); // NOI18N

        fancyLabel4.setText("19");
        fancyLabel4.setFont(new java.awt.Font("Ralika", 0, 36)); // NOI18N

        fancyLabel6.setText("+4");
        fancyLabel6.setFont(new java.awt.Font("Ralika", 0, 36)); // NOI18N

        fancyLabel9.setText("+4 this week");
        fancyLabel9.setFont(new java.awt.Font("Ralika", 0, 14)); // NOI18N

        javax.swing.GroupLayout fancyPanel16Layout = new javax.swing.GroupLayout(fancyPanel16);
        fancyPanel16.setLayout(fancyPanel16Layout);
        fancyPanel16Layout.setHorizontalGroup(
            fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel16Layout.createSequentialGroup()
                .addGroup(fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel16Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fancyLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1))))
                    .addGroup(fancyPanel16Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel16Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel16Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        fancyPanel16Layout.setVerticalGroup(
            fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel16Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel7Layout = new javax.swing.GroupLayout(fancyPanel7);
        fancyPanel7.setLayout(fancyPanel7Layout);
        fancyPanel7Layout.setHorizontalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel7Layout.createSequentialGroup()
                .addComponent(fancyPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        fancyPanel7Layout.setVerticalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel7Layout.createSequentialGroup()
                .addComponent(fancyPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 190, 240));

        jLabel23.setFont(new java.awt.Font("Super Bouncer", 0, 30)); // NOI18N
        jLabel23.setText("Recent Activity");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 240, 40));

        jLabel24.setFont(new java.awt.Font("Super Bouncer", 0, 30)); // NOI18N
        jLabel24.setText("Quick Actions");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 190, 40));

        jLabel25.setFont(new java.awt.Font("Super Bouncer", 0, 30)); // NOI18N
        jLabel25.setText("Admin Dashboard");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 250, 40));

        fancyPanel22.setGradientEnabled(false);
        fancyPanel22.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel22.setSolidBackgroundEnabled(true);

        fancyPanel23.setBorderEnabled(true);
        fancyPanel23.setGradientEnabled(false);
        fancyPanel23.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel23.setSolidBackgroundEnabled(true);

        fancyLabel22.setText("Manage");
        fancyLabel22.setFont(new java.awt.Font("Magesta", 0, 22)); // NOI18N

        fancyLabel18.setText("Users");
        fancyLabel18.setFont(new java.awt.Font("Magesta", 0, 22)); // NOI18N

        fancyButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fancyButton4.setText(">");
        fancyButton4.addActionListener(this::fancyButton4ActionPerformed);

        javax.swing.GroupLayout fancyPanel23Layout = new javax.swing.GroupLayout(fancyPanel23);
        fancyPanel23.setLayout(fancyPanel23Layout);
        fancyPanel23Layout.setHorizontalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel23Layout.createSequentialGroup()
                .addGroup(fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel23Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(fancyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel23Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(fancyLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(fancyButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        fancyPanel23Layout.setVerticalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel23Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(fancyLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout fancyPanel22Layout = new javax.swing.GroupLayout(fancyPanel22);
        fancyPanel22.setLayout(fancyPanel22Layout);
        fancyPanel22Layout.setHorizontalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addComponent(fancyPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        fancyPanel22Layout.setVerticalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addComponent(fancyPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(fancyPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 260, -1));

        fancyPanel24.setGradientEnabled(false);
        fancyPanel24.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel24.setSolidBackgroundEnabled(true);

        fancyPanel25.setBorderEnabled(true);
        fancyPanel25.setGradientEnabled(false);
        fancyPanel25.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel25.setSolidBackgroundEnabled(true);

        fancyLabel19.setText("New User Registered");
        fancyLabel19.setFont(new java.awt.Font("Magesta", 0, 20)); // NOI18N

        fancyButton2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        fancyButton2.setText(">");
        fancyButton2.addActionListener(this::fancyButton2ActionPerformed);

        javax.swing.GroupLayout fancyPanel25Layout = new javax.swing.GroupLayout(fancyPanel25);
        fancyPanel25.setLayout(fancyPanel25Layout);
        fancyPanel25Layout.setHorizontalGroup(
            fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel25Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(fancyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        fancyPanel25Layout.setVerticalGroup(
            fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel25Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fancyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel24Layout = new javax.swing.GroupLayout(fancyPanel24);
        fancyPanel24.setLayout(fancyPanel24Layout);
        fancyPanel24Layout.setHorizontalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel24Layout.createSequentialGroup()
                .addComponent(fancyPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        fancyPanel24Layout.setVerticalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel24Layout.createSequentialGroup()
                .addComponent(fancyPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 390, 50));

        fancyPanel15.setGradientEnabled(false);
        fancyPanel15.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel15.setSolidBackgroundEnabled(true);

        fancyPanel17.setBorderEnabled(true);
        fancyPanel17.setGradientEnabled(false);
        fancyPanel17.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel17.setSolidBackgroundEnabled(true);

        fancyLabel15.setText("Active Quiz");
        fancyLabel15.setFont(new java.awt.Font("Magesta", 0, 24)); // NOI18N

        fancyLabel3.setText("5");
        fancyLabel3.setFont(new java.awt.Font("Ralika", 0, 36)); // NOI18N

        fancyLabel7.setText("+3");
        fancyLabel7.setFont(new java.awt.Font("Ralika", 0, 36)); // NOI18N

        fancyLabel10.setText("+3 this week");
        fancyLabel10.setFont(new java.awt.Font("Ralika", 0, 14)); // NOI18N

        javax.swing.GroupLayout fancyPanel17Layout = new javax.swing.GroupLayout(fancyPanel17);
        fancyPanel17.setLayout(fancyPanel17Layout);
        fancyPanel17Layout.setHorizontalGroup(
            fancyPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel17Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(fancyPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel17Layout.createSequentialGroup()
                        .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel17Layout.createSequentialGroup()
                        .addGroup(fancyPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fancyLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5))
                        .addGap(21, 21, 21))))
            .addGroup(fancyPanel17Layout.createSequentialGroup()
                .addGroup(fancyPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel17Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel17Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(fancyPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fancyPanel17Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jSeparator2)
                    .addGap(21, 21, 21)))
        );
        fancyPanel17Layout.setVerticalGroup(
            fancyPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel17Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(fancyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(fancyPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fancyPanel17Layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(106, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout fancyPanel15Layout = new javax.swing.GroupLayout(fancyPanel15);
        fancyPanel15.setLayout(fancyPanel15Layout);
        fancyPanel15Layout.setHorizontalGroup(
            fancyPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel15Layout.createSequentialGroup()
                .addComponent(fancyPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        fancyPanel15Layout.setVerticalGroup(
            fancyPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel15Layout.createSequentialGroup()
                .addComponent(fancyPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, 240));

        fancyPanel18.setGradientEnabled(false);
        fancyPanel18.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel18.setSolidBackgroundEnabled(true);

        fancyPanel19.setBorderEnabled(true);
        fancyPanel19.setGradientEnabled(false);
        fancyPanel19.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel19.setSolidBackgroundEnabled(true);

        fancyLabel16.setText("Pending Quiz");
        fancyLabel16.setFont(new java.awt.Font("Magesta", 0, 22)); // NOI18N

        fancyLabel5.setText("1");
        fancyLabel5.setFont(new java.awt.Font("Ralika", 0, 36)); // NOI18N

        fancyLabel8.setText("-5");
        fancyLabel8.setFont(new java.awt.Font("Ralika", 0, 36)); // NOI18N

        fancyLabel11.setText("-5 this week");
        fancyLabel11.setFont(new java.awt.Font("Ralika", 0, 14)); // NOI18N

        javax.swing.GroupLayout fancyPanel19Layout = new javax.swing.GroupLayout(fancyPanel19);
        fancyPanel19.setLayout(fancyPanel19Layout);
        fancyPanel19Layout.setHorizontalGroup(
            fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel19Layout.createSequentialGroup()
                .addGroup(fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel19Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fancyPanel19Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fancyPanel19Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jSeparator3)
                    .addGap(21, 21, 21)))
        );
        fancyPanel19Layout.setVerticalGroup(
            fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel19Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(fancyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fancyPanel19Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(107, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout fancyPanel18Layout = new javax.swing.GroupLayout(fancyPanel18);
        fancyPanel18.setLayout(fancyPanel18Layout);
        fancyPanel18Layout.setHorizontalGroup(
            fancyPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel18Layout.createSequentialGroup()
                .addComponent(fancyPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        fancyPanel18Layout.setVerticalGroup(
            fancyPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel18Layout.createSequentialGroup()
                .addComponent(fancyPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, 240));

        fancyPanel28.setGradientEnabled(false);
        fancyPanel28.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel28.setSolidBackgroundEnabled(true);

        fancyPanel29.setBorderEnabled(true);
        fancyPanel29.setGradientEnabled(false);
        fancyPanel29.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel29.setSolidBackgroundEnabled(true);

        fancyLabel21.setText("Quiz Approved");
        fancyLabel21.setFont(new java.awt.Font("Magesta", 0, 20)); // NOI18N

        fancyButton3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        fancyButton3.setText(">");
        fancyButton3.addActionListener(this::fancyButton3ActionPerformed);

        javax.swing.GroupLayout fancyPanel29Layout = new javax.swing.GroupLayout(fancyPanel29);
        fancyPanel29.setLayout(fancyPanel29Layout);
        fancyPanel29Layout.setHorizontalGroup(
            fancyPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel29Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(fancyLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(fancyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        fancyPanel29Layout.setVerticalGroup(
            fancyPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel29Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(fancyPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fancyLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel28Layout = new javax.swing.GroupLayout(fancyPanel28);
        fancyPanel28.setLayout(fancyPanel28Layout);
        fancyPanel28Layout.setHorizontalGroup(
            fancyPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel28Layout.createSequentialGroup()
                .addComponent(fancyPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        fancyPanel28Layout.setVerticalGroup(
            fancyPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel28Layout.createSequentialGroup()
                .addComponent(fancyPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 390, -1));

        fancyPanel26.setGradientEnabled(false);
        fancyPanel26.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel26.setSolidBackgroundEnabled(true);

        fancyPanel27.setBorderEnabled(true);
        fancyPanel27.setGradientEnabled(false);
        fancyPanel27.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel27.setSolidBackgroundEnabled(true);

        fancyButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fancyButton5.setText(">");
        fancyButton5.addActionListener(this::fancyButton5ActionPerformed);

        fancyLabel20.setText("View");
        fancyLabel20.setFont(new java.awt.Font("Magesta", 0, 22)); // NOI18N

        fancyLabel17.setText("Reports");
        fancyLabel17.setFont(new java.awt.Font("Magesta", 0, 22)); // NOI18N

        javax.swing.GroupLayout fancyPanel27Layout = new javax.swing.GroupLayout(fancyPanel27);
        fancyPanel27.setLayout(fancyPanel27Layout);
        fancyPanel27Layout.setHorizontalGroup(
            fancyPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel27Layout.createSequentialGroup()
                .addGroup(fancyPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel27Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(fancyLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel27Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(fancyLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(fancyButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        fancyPanel27Layout.setVerticalGroup(
            fancyPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(fancyPanel27Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(fancyLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel26Layout = new javax.swing.GroupLayout(fancyPanel26);
        fancyPanel26.setLayout(fancyPanel26Layout);
        fancyPanel26Layout.setHorizontalGroup(
            fancyPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel26Layout.createSequentialGroup()
                .addComponent(fancyPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        fancyPanel26Layout.setVerticalGroup(
            fancyPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel26Layout.createSequentialGroup()
                .addComponent(fancyPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(fancyPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fancyButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton11ActionPerformed

    private void fancyButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton13ActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
int choice = JOptionPane.showConfirmDialog(this, "Are you sure to logout?" ,"Confirm logout", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new LogInn().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogOutActionPerformed

    private void fancyButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton12ActionPerformed

    private void fancyButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton2ActionPerformed

    private void fancyButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton3ActionPerformed

    private void fancyButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton4ActionPerformed

    private void fancyButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton LogOut;
    private fancyui.FancyButton fancyButton10;
    private fancyui.FancyButton fancyButton11;
    private fancyui.FancyButton fancyButton12;
    private fancyui.FancyButton fancyButton13;
    private fancyui.FancyButton fancyButton14;
    private fancyui.FancyButton fancyButton2;
    private fancyui.FancyButton fancyButton3;
    private fancyui.FancyButton fancyButton4;
    private fancyui.FancyButton fancyButton5;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyImage fancyImage7;
    private fancyui.FancyLabel fancyLabel10;
    private fancyui.FancyLabel fancyLabel11;
    private fancyui.FancyLabel fancyLabel14;
    private fancyui.FancyLabel fancyLabel15;
    private fancyui.FancyLabel fancyLabel16;
    private fancyui.FancyLabel fancyLabel17;
    private fancyui.FancyLabel fancyLabel18;
    private fancyui.FancyLabel fancyLabel19;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel20;
    private fancyui.FancyLabel fancyLabel21;
    private fancyui.FancyLabel fancyLabel22;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel4;
    private fancyui.FancyLabel fancyLabel5;
    private fancyui.FancyLabel fancyLabel6;
    private fancyui.FancyLabel fancyLabel7;
    private fancyui.FancyLabel fancyLabel8;
    private fancyui.FancyLabel fancyLabel9;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel15;
    private fancyui.FancyPanel fancyPanel16;
    private fancyui.FancyPanel fancyPanel17;
    private fancyui.FancyPanel fancyPanel18;
    private fancyui.FancyPanel fancyPanel19;
    private fancyui.FancyPanel fancyPanel22;
    private fancyui.FancyPanel fancyPanel23;
    private fancyui.FancyPanel fancyPanel24;
    private fancyui.FancyPanel fancyPanel25;
    private fancyui.FancyPanel fancyPanel26;
    private fancyui.FancyPanel fancyPanel27;
    private fancyui.FancyPanel fancyPanel28;
    private fancyui.FancyPanel fancyPanel29;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyPanel fancyPanel7;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
