/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lyza
 */
public class CreateAccount extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateAccount.class.getName());

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fancyLabel1 = new fancyui.FancyLabel();
        jLabel5 = new javax.swing.JLabel();
        fancyImage2 = new fancyui.FancyImage();
        fancyPanel1 = new fancyui.FancyPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userfield = new fancyui.FancyTextField();
        passfield = new fancyui.FancyPasswordField();
        jLabel1 = new javax.swing.JLabel();
        fancyButton1 = new fancyui.FancyButton();
        userfield1 = new fancyui.FancyTextField();
        userfield2 = new fancyui.FancyTextField();
        role = new javax.swing.JComboBox<>();
        fancyImage3 = new fancyui.FancyImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fancyLabel1.setForeground(new java.awt.Color(245, 197, 66));
        fancyLabel1.setText("LUMINEX");
        fancyLabel1.setFont(new java.awt.Font("Super Bouncer", 0, 29)); // NOI18N
        jPanel2.add(fancyLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Winter Poppins", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 17, 63));
        jLabel5.setText("Challenge You Mind, Light Up your knowledge");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 280, 30));

        fancyImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/774148120_1731905104754691_9160798377654078668_n.png"))); // NOI18N
        fancyImage2.setScaleType(fancyui.FancyImage.ScaleType.FIT);
        fancyImage2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fancyImage2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(fancyImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 370, 230));

        fancyPanel1.setBorderColor(new java.awt.Color(255, 255, 255));
        fancyPanel1.setBorderEnabled(true);
        fancyPanel1.setBorderThickness(1.75F);
        fancyPanel1.setBottomLeftRadius(20);
        fancyPanel1.setBottomRightRadius(20);
        fancyPanel1.setCornerRadius(20);
        fancyPanel1.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel1.setGradientStart(new java.awt.Color(148, 51, 196));
        fancyPanel1.setOpacity(0.6F);
        fancyPanel1.setSolidBackgroundEnabled(true);

        jLabel2.setFont(new java.awt.Font("Winter Poppins", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 17, 63));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-test-account-24.png"))); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        userfield.setBackgroundColor(new java.awt.Color(204, 204, 249));
        userfield.setBorderEnabled(false);
        userfield.setBorderStyle(null);
        userfield.setCornerRadius(7);
        userfield.setFocusBorderColor(java.awt.Color.white);
        userfield.setPlaceholder("Username");
        userfield.setPlaceholderColor(new java.awt.Color(0, 0, 0));
        userfield.addActionListener(this::userfieldActionPerformed);

        passfield.setBackgroundColor(new java.awt.Color(204, 204, 249));
        passfield.setBorderEnabled(false);
        passfield.setCornerRadius(7);
        passfield.setPlaceholderColor(new java.awt.Color(0, 0, 0));
        passfield.addActionListener(this::passfieldActionPerformed);

        jLabel1.setFont(new java.awt.Font("Super Bouncer", 0, 36)); // NOI18N
        jLabel1.setText("Create Account");

        fancyButton1.setText("Create Account");
        fancyButton1.setBackgroundColor(new java.awt.Color(204, 204, 249));
        fancyButton1.setBorderEnabled(false);
        fancyButton1.setCornerRadius(7);
        fancyButton1.setHoverBackground(new java.awt.Color(191, 162, 255));
        fancyButton1.addActionListener(this::fancyButton1ActionPerformed);

        userfield1.setBackgroundColor(new java.awt.Color(204, 204, 249));
        userfield1.setBorderEnabled(false);
        userfield1.setBorderStyle(null);
        userfield1.setCornerRadius(7);
        userfield1.setFocusBorderColor(java.awt.Color.white);
        userfield1.setPlaceholder("Phone No.");
        userfield1.setPlaceholderColor(new java.awt.Color(0, 0, 0));
        userfield1.addActionListener(this::userfield1ActionPerformed);

        userfield2.setBackgroundColor(new java.awt.Color(204, 204, 249));
        userfield2.setBorderEnabled(false);
        userfield2.setBorderStyle(null);
        userfield2.setCornerRadius(7);
        userfield2.setFocusBorderColor(java.awt.Color.white);
        userfield2.setPlaceholder("Gmail");
        userfield2.setPlaceholderColor(new java.awt.Color(0, 0, 0));
        userfield2.addActionListener(this::userfield2ActionPerformed);

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher" }));
        role.addActionListener(this::roleActionPerformed);

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel1Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userfield, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(221, 221, 221))
                                .addComponent(role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(fancyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(553, 553, 553))
        );

        jPanel2.add(fancyPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 320, 420));

        fancyImage3.setBorderColor(new java.awt.Color(255, 255, 255));
        fancyImage3.setBorderEnabled(true);
        fancyImage3.setBorderThickness(0.0F);
        fancyImage3.setCornerRadius(0);
        fancyImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dola (2).png"))); // NOI18N
        jPanel2.add(fancyImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 710));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fancyImage2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fancyImage2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyImage2AncestorAdded

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void fancyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton1ActionPerformed

    }//GEN-LAST:event_fancyButton1ActionPerformed

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void userfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfield1ActionPerformed

    private void userfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfield2ActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
       
    }//GEN-LAST:event_roleActionPerformed

    private void passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateAccount().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton fancyButton1;
    private fancyui.FancyImage fancyImage2;
    private fancyui.FancyImage fancyImage3;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyPanel fancyPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private fancyui.FancyPasswordField passfield;
    private javax.swing.JComboBox<String> role;
    private fancyui.FancyTextField userfield;
    private fancyui.FancyTextField userfield1;
    private fancyui.FancyTextField userfield2;
    // End of variables declaration//GEN-END:variables
}
