
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lyza
 */
public class Dashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyImage1 = new fancyui.FancyImage();
        fancyButton1 = new fancyui.FancyButton();
        fancyButton2 = new fancyui.FancyButton();
        fancyButton3 = new fancyui.FancyButton();
        fancyButton4 = new fancyui.FancyButton();
        fancyButton5 = new fancyui.FancyButton();
        fancyLabel2 = new fancyui.FancyLabel();
        fancyButton9 = new fancyui.FancyButton();
        LogOut = new fancyui.FancyButton();
        fancyPanel3 = new fancyui.FancyPanel();
        fancyLabel1 = new fancyui.FancyLabel();
        fancyButton7 = new fancyui.FancyButton();
        fancyPanel4 = new fancyui.FancyPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fancyImage7 = new fancyui.FancyImage();
        jLabel21 = new javax.swing.JLabel();
        fancyLabel3 = new fancyui.FancyLabel();
        fancyPanel18 = new fancyui.FancyPanel();
        fancyPanel19 = new fancyui.FancyPanel();
        fancyLabel16 = new fancyui.FancyLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        fancyPanel20 = new fancyui.FancyPanel();
        fancyPanel8 = new fancyui.FancyPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fancyPanel9 = new fancyui.FancyPanel();
        fancyImage2 = new fancyui.FancyImage();
        fancyLabel9 = new fancyui.FancyLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fancyImage5 = new fancyui.FancyImage();
        fancyPanel22 = new fancyui.FancyPanel();
        fancyPanel23 = new fancyui.FancyPanel();
        fancyLabel18 = new fancyui.FancyLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fancyPanel24 = new fancyui.FancyPanel();
        fancyPanel25 = new fancyui.FancyPanel();
        fancyLabel19 = new fancyui.FancyLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        fancyPanel21 = new fancyui.FancyPanel();
        fancyPanel26 = new fancyui.FancyPanel();
        fancyPanel7 = new fancyui.FancyPanel();
        fancyPanel14 = new fancyui.FancyPanel();
        fancyImage11 = new fancyui.FancyImage();
        fancyLabel14 = new fancyui.FancyLabel();
        fancyImage12 = new fancyui.FancyImage();
        fancyImage13 = new fancyui.FancyImage();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fancyPanel1.setBorderColor(new java.awt.Color(228, 212, 238));
        fancyPanel1.setBorderEnabled(true);
        fancyPanel1.setBottomLeftRadius(0);
        fancyPanel1.setBottomRightRadius(0);
        fancyPanel1.setCornerRadius(0);
        fancyPanel1.setGradientEnd(new java.awt.Color(241, 223, 250));
        fancyPanel1.setGradientStart(new java.awt.Color(186, 130, 213));
        fancyPanel1.setSolidBackgroundColor(new java.awt.Color(229, 216, 236));
        fancyPanel1.setSolidBackgroundEnabled(true);

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/774148120_1731905104754691_9160798377654078668_n.png"))); // NOI18N
        fancyImage1.setScaleType(fancyui.FancyImage.ScaleType.FIT);

        fancyButton1.setText("Home");
        fancyButton1.setBorderEnabled(false);
        fancyButton1.setCornerRadius(13);
        fancyButton1.setHoverBackground(new java.awt.Color(145, 92, 232));

        fancyButton2.setText("Start Quiz");
        fancyButton2.setBorderEnabled(false);
        fancyButton2.setCornerRadius(13);
        fancyButton2.setHoverBackground(new java.awt.Color(145, 92, 232));

        fancyButton3.setText("View Result");
        fancyButton3.setBorderEnabled(false);
        fancyButton3.setCornerRadius(13);
        fancyButton3.setHoverBackground(new java.awt.Color(145, 92, 232));

        fancyButton4.setText("Review Quiz");
        fancyButton4.setBorderEnabled(false);
        fancyButton4.setCornerRadius(13);
        fancyButton4.setHoverBackground(new java.awt.Color(145, 92, 232));
        fancyButton4.addActionListener(this::fancyButton4ActionPerformed);

        fancyButton5.setText("Leaderboard");
        fancyButton5.setBorderEnabled(false);
        fancyButton5.setCornerRadius(13);
        fancyButton5.setHoverBackground(new java.awt.Color(145, 92, 232));

        fancyLabel2.setForeground(new java.awt.Color(202, 143, 232));
        fancyLabel2.setText("LUMINEX");
        fancyLabel2.setFont(new java.awt.Font("Super Bouncer", 0, 24)); // NOI18N

        fancyButton9.setText("Profile");
        fancyButton9.setBorderEnabled(false);
        fancyButton9.setCornerRadius(13);
        fancyButton9.setHoverBackground(new java.awt.Color(145, 92, 232));

        LogOut.setText("Logout");
        LogOut.setBorderEnabled(false);
        LogOut.setCornerRadius(10);
        LogOut.setHoverBackground(new java.awt.Color(145, 92, 232));
        LogOut.addActionListener(this::LogOutActionPerformed);

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fancyButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(fancyButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(fancyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jPanel1.add(fancyPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 710));

        fancyPanel3.setBorderColor(new java.awt.Color(203, 187, 238));
        fancyPanel3.setBorderEnabled(true);
        fancyPanel3.setBorderThickness(2.0F);
        fancyPanel3.setGradientAngle(360);
        fancyPanel3.setGradientEnd(new java.awt.Color(228, 212, 238));
        fancyPanel3.setGradientStart(new java.awt.Color(203, 187, 238));
        fancyPanel3.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));

        fancyLabel1.setForeground(new java.awt.Color(255, 255, 255));
        fancyLabel1.setText("Ready for Quiz?");
        fancyLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        fancyButton7.setFont(new java.awt.Font("Winter Poppins", 0, 16)); // NOI18N
        fancyButton7.setText("Start Now");
        fancyButton7.setBorderColor(new java.awt.Color(245, 197, 66));
        fancyButton7.setBorderEnabled(false);
        fancyButton7.setBottomLeftRadius(9);
        fancyButton7.setCornerRadius(9);
        fancyButton7.setGradientAngle(360);
        fancyButton7.setGradientEnabled(true);
        fancyButton7.setGradientEnd(new java.awt.Color(250, 215, 117));
        fancyButton7.setGradientStart(new java.awt.Color(255, 255, 204));
        fancyButton7.setHoverBackground(new java.awt.Color(252, 216, 115));
        fancyButton7.addActionListener(this::fancyButton7ActionPerformed);

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGroup(fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(fancyButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(fancyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 380, 120));

        fancyPanel4.setBorderColor(new java.awt.Color(241, 241, 241));
        fancyPanel4.setBorderEnabled(true);
        fancyPanel4.setCornerRadius(0);
        fancyPanel4.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel4.setSolidBackgroundEnabled(true);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel1.setText("Student");

        jLabel22.setFont(new java.awt.Font("Winter Poppins", 0, 18)); // NOI18N
        jLabel22.setText("LUMINEX Quiz System");

        fancyImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-test-account-24.png"))); // NOI18N

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(fancyImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(fancyPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 730, 40));

        jLabel21.setFont(new java.awt.Font("Super Bouncer", 0, 40)); // NOI18N
        jLabel21.setText("WELCOME BACK!");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 270, -1));

        fancyLabel3.setText("Recent Activity");
        fancyLabel3.setFont(new java.awt.Font("Super Bouncer", 0, 40)); // NOI18N
        jPanel1.add(fancyLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 270, -1));

        fancyPanel18.setGradientEnabled(false);
        fancyPanel18.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel18.setSolidBackgroundEnabled(true);

        fancyPanel19.setBorderEnabled(true);
        fancyPanel19.setGradientEnabled(false);
        fancyPanel19.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel19.setSolidBackgroundEnabled(true);

        fancyLabel16.setText("ITE");
        fancyLabel16.setFont(new java.awt.Font("Magesta", 0, 22)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel3.setText("Score:      95%");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setText("Status:");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("Passed");

        javax.swing.GroupLayout fancyPanel19Layout = new javax.swing.GroupLayout(fancyPanel19);
        fancyPanel19.setLayout(fancyPanel19Layout);
        fancyPanel19Layout.setHorizontalGroup(
            fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel19Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addComponent(jSeparator4)
            .addGroup(fancyPanel19Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(fancyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel19Layout.setVerticalGroup(
            fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel18Layout = new javax.swing.GroupLayout(fancyPanel18);
        fancyPanel18.setLayout(fancyPanel18Layout);
        fancyPanel18Layout.setHorizontalGroup(
            fancyPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel18Layout.createSequentialGroup()
                .addComponent(fancyPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        fancyPanel18Layout.setVerticalGroup(
            fancyPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel18Layout.createSequentialGroup()
                .addComponent(fancyPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 170, 150));

        fancyPanel20.setGradientEnabled(false);
        fancyPanel20.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel20.setSolidBackgroundEnabled(true);

        fancyPanel8.setBorderEnabled(true);
        fancyPanel8.setBorderThickness(2.0F);
        fancyPanel8.setGradientAngle(180);
        fancyPanel8.setGradientEnabled(false);
        fancyPanel8.setGradientEnd(new java.awt.Color(233, 168, 250));
        fancyPanel8.setGradientStart(new java.awt.Color(253, 217, 253));
        fancyPanel8.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel8.setSolidBackgroundEnabled(true);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel15.setText("75% ");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("9 / 12 Quizzes");

        fancyPanel9.setBorderEnabled(true);
        fancyPanel9.setBorderThickness(2.0F);
        fancyPanel9.setBottomLeftRadius(0);
        fancyPanel9.setBottomRightRadius(0);
        fancyPanel9.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel9.setSolidBackgroundEnabled(true);

        fancyImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-in-progress-24.png"))); // NOI18N

        fancyLabel9.setBackground(new java.awt.Color(204, 204, 255));
        fancyLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fancyLabel9.setText("Progress");
        fancyLabel9.setFont(new java.awt.Font("Winter Poppins", 1, 36)); // NOI18N

        javax.swing.GroupLayout fancyPanel9Layout = new javax.swing.GroupLayout(fancyPanel9);
        fancyPanel9.setLayout(fancyPanel9Layout);
        fancyPanel9Layout.setHorizontalGroup(
            fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        fancyPanel9Layout.setVerticalGroup(
            fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel9Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(fancyPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fancyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("3 Pending");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel16.setText("Completed");

        fancyImage5.setCornerRadius(0);
        fancyImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pending-48.png"))); // NOI18N

        javax.swing.GroupLayout fancyPanel8Layout = new javax.swing.GroupLayout(fancyPanel8);
        fancyPanel8.setLayout(fancyPanel8Layout);
        fancyPanel8Layout.setHorizontalGroup(
            fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fancyPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(29, 29, 29))
            .addGroup(fancyPanel8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(fancyPanel8Layout.createSequentialGroup()
                        .addComponent(fancyImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel8Layout.setVerticalGroup(
            fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel8Layout.createSequentialGroup()
                .addComponent(fancyPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(fancyPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(fancyImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout fancyPanel20Layout = new javax.swing.GroupLayout(fancyPanel20);
        fancyPanel20.setLayout(fancyPanel20Layout);
        fancyPanel20Layout.setHorizontalGroup(
            fancyPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel20Layout.createSequentialGroup()
                .addComponent(fancyPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        fancyPanel20Layout.setVerticalGroup(
            fancyPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel20Layout.createSequentialGroup()
                .addComponent(fancyPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 210, 310));

        fancyPanel22.setGradientEnabled(false);
        fancyPanel22.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel22.setSolidBackgroundEnabled(true);

        fancyPanel23.setBorderEnabled(true);
        fancyPanel23.setGradientEnabled(false);
        fancyPanel23.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel23.setSolidBackgroundEnabled(true);

        fancyLabel18.setText("IPT");
        fancyLabel18.setFont(new java.awt.Font("Magesta", 0, 22)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel10.setText("Score:      85%");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel13.setText("Status:");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 51));
        jLabel14.setText("Passed");

        javax.swing.GroupLayout fancyPanel23Layout = new javax.swing.GroupLayout(fancyPanel23);
        fancyPanel23.setLayout(fancyPanel23Layout);
        fancyPanel23Layout.setHorizontalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel23Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel23Layout.createSequentialGroup()
                        .addGroup(fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fancyPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel23Layout.createSequentialGroup()
                        .addComponent(fancyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        fancyPanel23Layout.setVerticalGroup(
            fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel22Layout = new javax.swing.GroupLayout(fancyPanel22);
        fancyPanel22.setLayout(fancyPanel22Layout);
        fancyPanel22Layout.setHorizontalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addComponent(fancyPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel22Layout.setVerticalGroup(
            fancyPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel22Layout.createSequentialGroup()
                .addComponent(fancyPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(fancyPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 170, 150));

        fancyPanel24.setGradientEnabled(false);
        fancyPanel24.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel24.setSolidBackgroundEnabled(true);

        fancyPanel25.setBorderEnabled(true);
        fancyPanel25.setGradientEnabled(false);
        fancyPanel25.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel25.setSolidBackgroundEnabled(true);

        fancyLabel19.setText("CC104");
        fancyLabel19.setFont(new java.awt.Font("Magesta", 0, 22)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel26.setText("Score:      90%");

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel27.setText("Status:");

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 51));
        jLabel28.setText("Passed");

        javax.swing.GroupLayout fancyPanel25Layout = new javax.swing.GroupLayout(fancyPanel25);
        fancyPanel25.setLayout(fancyPanel25Layout);
        fancyPanel25Layout.setHorizontalGroup(
            fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel25Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel25Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addContainerGap())
                    .addGroup(fancyPanel25Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
            .addComponent(jSeparator2)
            .addGroup(fancyPanel25Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(fancyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fancyPanel25Layout.setVerticalGroup(
            fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fancyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fancyPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel24Layout = new javax.swing.GroupLayout(fancyPanel24);
        fancyPanel24.setLayout(fancyPanel24Layout);
        fancyPanel24Layout.setHorizontalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel24Layout.createSequentialGroup()
                .addComponent(fancyPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel24Layout.setVerticalGroup(
            fancyPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel24Layout.createSequentialGroup()
                .addComponent(fancyPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(fancyPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 170, 150));

        fancyPanel21.setGradientEnabled(false);
        fancyPanel21.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel21.setSolidBackgroundEnabled(true);

        javax.swing.GroupLayout fancyPanel21Layout = new javax.swing.GroupLayout(fancyPanel21);
        fancyPanel21.setLayout(fancyPanel21Layout);
        fancyPanel21Layout.setHorizontalGroup(
            fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        fancyPanel21Layout.setVerticalGroup(
            fancyPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(fancyPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 390, 130));

        fancyPanel26.setGradientEnabled(false);
        fancyPanel26.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel26.setSolidBackgroundEnabled(true);

        fancyPanel7.setBorderEnabled(true);
        fancyPanel7.setBorderThickness(2.0F);
        fancyPanel7.setGradientAngle(180);
        fancyPanel7.setGradientEnabled(false);
        fancyPanel7.setGradientEnd(new java.awt.Color(233, 168, 250));
        fancyPanel7.setGradientStart(new java.awt.Color(253, 217, 253));
        fancyPanel7.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel7.setSolidBackgroundEnabled(true);

        fancyPanel14.setBorderEnabled(true);
        fancyPanel14.setBorderThickness(2.0F);
        fancyPanel14.setBottomLeftRadius(0);
        fancyPanel14.setBottomRightRadius(0);
        fancyPanel14.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel14.setSolidBackgroundEnabled(true);

        fancyImage11.setCornerRadius(0);
        fancyImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-rating-50.png"))); // NOI18N

        fancyLabel14.setBackground(new java.awt.Color(204, 204, 255));
        fancyLabel14.setText("My Rank");
        fancyLabel14.setFont(new java.awt.Font("Winter Poppins", 1, 36)); // NOI18N

        javax.swing.GroupLayout fancyPanel14Layout = new javax.swing.GroupLayout(fancyPanel14);
        fancyPanel14.setLayout(fancyPanel14Layout);
        fancyPanel14Layout.setHorizontalGroup(
            fancyPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel14Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(fancyImage11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel14Layout.setVerticalGroup(
            fancyPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel14Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(fancyPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fancyImage11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        fancyImage12.setCornerRadius(0);
        fancyImage12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-warranty-48.png"))); // NOI18N

        fancyImage13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-trophy-64.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel32.setText("of all students");

        jLabel33.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel33.setText("Top 20%");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel34.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel34.setText("#18");

        javax.swing.GroupLayout fancyPanel7Layout = new javax.swing.GroupLayout(fancyPanel7);
        fancyPanel7.setLayout(fancyPanel7Layout);
        fancyPanel7Layout.setHorizontalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fancyImage12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyImage13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(36, 36, 36))
            .addComponent(fancyPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fancyPanel7Layout.setVerticalGroup(
            fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel7Layout.createSequentialGroup()
                .addComponent(fancyPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fancyPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel32))
                        .addComponent(fancyImage12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(fancyPanel7Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel34))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                    .addComponent(fancyImage13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fancyPanel26Layout = new javax.swing.GroupLayout(fancyPanel26);
        fancyPanel26.setLayout(fancyPanel26Layout);
        fancyPanel26Layout.setHorizontalGroup(
            fancyPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel26Layout.createSequentialGroup()
                .addComponent(fancyPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        fancyPanel26Layout.setVerticalGroup(
            fancyPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel26Layout.createSequentialGroup()
                .addComponent(fancyPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 390, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fancyButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton7ActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure to logout?", "Confirm logout", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new LogInn().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_LogOutActionPerformed
    }
    private void fancyButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton LogOut;
    private fancyui.FancyButton fancyButton1;
    private fancyui.FancyButton fancyButton2;
    private fancyui.FancyButton fancyButton3;
    private fancyui.FancyButton fancyButton4;
    private fancyui.FancyButton fancyButton5;
    private fancyui.FancyButton fancyButton7;
    private fancyui.FancyButton fancyButton9;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyImage fancyImage11;
    private fancyui.FancyImage fancyImage12;
    private fancyui.FancyImage fancyImage13;
    private fancyui.FancyImage fancyImage2;
    private fancyui.FancyImage fancyImage5;
    private fancyui.FancyImage fancyImage7;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyLabel fancyLabel14;
    private fancyui.FancyLabel fancyLabel16;
    private fancyui.FancyLabel fancyLabel18;
    private fancyui.FancyLabel fancyLabel19;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel3;
    private fancyui.FancyLabel fancyLabel9;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel14;
    private fancyui.FancyPanel fancyPanel18;
    private fancyui.FancyPanel fancyPanel19;
    private fancyui.FancyPanel fancyPanel20;
    private fancyui.FancyPanel fancyPanel21;
    private fancyui.FancyPanel fancyPanel22;
    private fancyui.FancyPanel fancyPanel23;
    private fancyui.FancyPanel fancyPanel24;
    private fancyui.FancyPanel fancyPanel25;
    private fancyui.FancyPanel fancyPanel26;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyPanel fancyPanel7;
    private fancyui.FancyPanel fancyPanel8;
    private fancyui.FancyPanel fancyPanel9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
