
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lyza
 */
public class DashboardTeachert extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardTeachert.class.getName());

    /**
     * Creates new form DashboardTeachert
     */
    public DashboardTeachert() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fancyTable1 = new fancyui.FancyTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        fancyPanel4 = new fancyui.FancyPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fancyImage7 = new fancyui.FancyImage();
        fancyButton7 = new fancyui.FancyButton();
        fancyButton8 = new fancyui.FancyButton();
        fancyPanel1 = new fancyui.FancyPanel();
        fancyImage1 = new fancyui.FancyImage();
        fancyButton10 = new fancyui.FancyButton();
        fancyButton11 = new fancyui.FancyButton();
        fancyButton12 = new fancyui.FancyButton();
        fancyButton13 = new fancyui.FancyButton();
        fancyButton14 = new fancyui.FancyButton();
        fancyLabel2 = new fancyui.FancyLabel();
        fancyButton15 = new fancyui.FancyButton();
        LogOut = new fancyui.FancyButton();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fancyTable2 = new fancyui.FancyTable();
        fancyPanel10 = new fancyui.FancyPanel();
        fancyPanel16 = new fancyui.FancyPanel();
        fancyLabel14 = new fancyui.FancyLabel();
        fancyLabel12 = new fancyui.FancyLabel();
        fancyLabel15 = new fancyui.FancyLabel();
        fancyImage2 = new fancyui.FancyImage();
        fancyPanel12 = new fancyui.FancyPanel();
        fancyPanel18 = new fancyui.FancyPanel();
        fancyLabel18 = new fancyui.FancyLabel();
        fancyLabel19 = new fancyui.FancyLabel();
        fancyLabel20 = new fancyui.FancyLabel();
        fancyImage6 = new fancyui.FancyImage();
        fancyPanel13 = new fancyui.FancyPanel();
        fancyPanel19 = new fancyui.FancyPanel();
        fancyLabel21 = new fancyui.FancyLabel();
        fancyLabel22 = new fancyui.FancyLabel();
        fancyLabel23 = new fancyui.FancyLabel();
        fancyImage5 = new fancyui.FancyImage();
        fancyPanel2 = new fancyui.FancyPanel();
        fancyPanel3 = new fancyui.FancyPanel();

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel1.setText("Teacher");

        fancyTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(fancyTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Super Bouncer", 0, 30)); // NOI18N
        jLabel21.setText("Quiz Performance Overview");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 450, 40));

        fancyPanel4.setBorderColor(new java.awt.Color(241, 241, 241));
        fancyPanel4.setBorderEnabled(true);
        fancyPanel4.setCornerRadius(0);
        fancyPanel4.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel4.setSolidBackgroundEnabled(true);

        jLabel16.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel16.setText("Teacher");

        jLabel22.setFont(new java.awt.Font("Winter Poppins", 0, 18)); // NOI18N
        jLabel22.setText("LUMINEX Quiz System");

        fancyImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-test-account-24.png"))); // NOI18N

        javax.swing.GroupLayout fancyPanel4Layout = new javax.swing.GroupLayout(fancyPanel4);
        fancyPanel4.setLayout(fancyPanel4Layout);
        fancyPanel4Layout.setHorizontalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fancyPanel4Layout.setVerticalGroup(
            fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(fancyPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fancyPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(fancyImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(fancyPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 730, 40));

        fancyButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fancyButton7.setText("Create Quiz");
        fancyButton7.setCornerRadius(9);
        fancyButton7.setGradientEnabled(true);
        fancyButton7.setGradientEnd(new java.awt.Color(228, 212, 238));
        fancyButton7.setGradientStart(new java.awt.Color(203, 187, 238));
        fancyButton7.setHoverBackground(new java.awt.Color(145, 92, 232));
        fancyButton7.addActionListener(this::fancyButton7ActionPerformed);
        jPanel1.add(fancyButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 190, 40));

        fancyButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fancyButton8.setText("Add New Lesson");
        fancyButton8.setCornerRadius(9);
        fancyButton8.setGradientEnabled(true);
        fancyButton8.setGradientEnd(new java.awt.Color(228, 212, 238));
        fancyButton8.setGradientStart(new java.awt.Color(203, 187, 238));
        fancyButton8.setHoverBackground(new java.awt.Color(145, 92, 232));
        fancyButton8.addActionListener(this::fancyButton8ActionPerformed);
        jPanel1.add(fancyButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 190, 40));

        fancyPanel1.setBorderColor(new java.awt.Color(228, 212, 238));
        fancyPanel1.setBorderEnabled(true);
        fancyPanel1.setBottomLeftRadius(0);
        fancyPanel1.setBottomRightRadius(0);
        fancyPanel1.setCornerRadius(0);
        fancyPanel1.setGradientEnd(new java.awt.Color(241, 223, 250));
        fancyPanel1.setGradientStart(new java.awt.Color(186, 130, 213));
        fancyPanel1.setSolidBackgroundColor(new java.awt.Color(229, 216, 236));
        fancyPanel1.setSolidBackgroundEnabled(true);

        fancyImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/774148120_1731905104754691_9160798377654078668_n.png"))); // NOI18N
        fancyImage1.setScaleType(fancyui.FancyImage.ScaleType.FIT);

        fancyButton10.setText("Home");
        fancyButton10.setBorderEnabled(false);
        fancyButton10.setCornerRadius(13);
        fancyButton10.setHoverBackground(new java.awt.Color(145, 92, 232));

        fancyButton11.setText("Add lesson");
        fancyButton11.setBorderEnabled(false);
        fancyButton11.setCornerRadius(13);
        fancyButton11.setHoverBackground(new java.awt.Color(145, 92, 232));
        fancyButton11.addActionListener(this::fancyButton11ActionPerformed);

        fancyButton12.setText("View Quiz");
        fancyButton12.setBorderEnabled(false);
        fancyButton12.setCornerRadius(13);
        fancyButton12.setHoverBackground(new java.awt.Color(145, 92, 232));
        fancyButton12.addActionListener(this::fancyButton12ActionPerformed);

        fancyButton13.setText("View Result");
        fancyButton13.setBorderEnabled(false);
        fancyButton13.setCornerRadius(13);
        fancyButton13.setHoverBackground(new java.awt.Color(145, 92, 232));
        fancyButton13.addActionListener(this::fancyButton13ActionPerformed);

        fancyButton14.setText("Leaderboard");
        fancyButton14.setBorderEnabled(false);
        fancyButton14.setCornerRadius(13);
        fancyButton14.setHoverBackground(new java.awt.Color(145, 92, 232));

        fancyLabel2.setForeground(new java.awt.Color(202, 143, 232));
        fancyLabel2.setText("LUMINEX");
        fancyLabel2.setFont(new java.awt.Font("Super Bouncer", 0, 24)); // NOI18N

        fancyButton15.setText("Profile");
        fancyButton15.setBorderEnabled(false);
        fancyButton15.setCornerRadius(13);
        fancyButton15.setHoverBackground(new java.awt.Color(145, 92, 232));

        LogOut.setText("Logout");
        LogOut.setBorderEnabled(false);
        LogOut.setCornerRadius(10);
        LogOut.setHoverBackground(new java.awt.Color(145, 92, 232));
        LogOut.addActionListener(this::LogOutActionPerformed);

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fancyButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(fancyButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fancyButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fancyImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(fancyButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fancyButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jPanel1.add(fancyPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 710));

        jLabel23.setFont(new java.awt.Font("Super Bouncer", 0, 36)); // NOI18N
        jLabel23.setText("Teacher Dashboard");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 310, 40));

        fancyTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Millante, Kyle Benin",  new Integer(1), "100%"},
                {"Barotillo, Princess Rocel",  new Integer(2), "98%"},
                {"Sanchez, Zyra Mae",  new Integer(3), "97%"},
                {"Obida, Lyza Kate",  new Integer(4), "95%"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Ranking", "Percentage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        fancyTable2.setEvenRowColor(new java.awt.Color(229, 216, 236));
        fancyTable2.setGradientEnd(new java.awt.Color(0, 0, 0));
        fancyTable2.setGradientStart(new java.awt.Color(0, 0, 0));
        fancyTable2.setGridLineColor(new java.awt.Color(0, 0, 0));
        fancyTable2.setHeaderBackground(new java.awt.Color(247, 249, 252));
        fancyTable2.setStripedRowsEnabled(true);
        jScrollPane2.setViewportView(fancyTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 560, 200));

        fancyPanel10.setGradientEnabled(false);
        fancyPanel10.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel10.setSolidBackgroundEnabled(true);

        fancyPanel16.setBorderEnabled(true);
        fancyPanel16.setGradientEnabled(false);
        fancyPanel16.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel16.setSolidBackgroundEnabled(true);

        fancyLabel14.setText("QUIZZES");
        fancyLabel14.setFont(new java.awt.Font("Magesta", 0, 20)); // NOI18N

        fancyLabel12.setText("5");
        fancyLabel12.setFont(new java.awt.Font("Ralika", 0, 36)); // NOI18N

        fancyLabel15.setText("CREATED");
        fancyLabel15.setFont(new java.awt.Font("Magesta", 0, 20)); // NOI18N

        fancyImage2.setCornerRadius(0);
        fancyImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-papers-48.png"))); // NOI18N

        javax.swing.GroupLayout fancyPanel16Layout = new javax.swing.GroupLayout(fancyPanel16);
        fancyPanel16.setLayout(fancyPanel16Layout);
        fancyPanel16Layout.setHorizontalGroup(
            fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel16Layout.createSequentialGroup()
                .addGroup(fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel16Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fancyPanel16Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel16Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        fancyPanel16Layout.setVerticalGroup(
            fancyPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel16Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(fancyImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout fancyPanel10Layout = new javax.swing.GroupLayout(fancyPanel10);
        fancyPanel10.setLayout(fancyPanel10Layout);
        fancyPanel10Layout.setHorizontalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel10Layout.createSequentialGroup()
                .addComponent(fancyPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        fancyPanel10Layout.setVerticalGroup(
            fancyPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel10Layout.createSequentialGroup()
                .addComponent(fancyPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 160, 190));

        fancyPanel12.setGradientEnabled(false);
        fancyPanel12.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel12.setSolidBackgroundEnabled(true);

        fancyPanel18.setBorderEnabled(true);
        fancyPanel18.setGradientEnabled(false);
        fancyPanel18.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel18.setSolidBackgroundEnabled(true);

        fancyLabel18.setText("LESSON");
        fancyLabel18.setFont(new java.awt.Font("Magesta", 0, 20)); // NOI18N

        fancyLabel19.setText("12");
        fancyLabel19.setFont(new java.awt.Font("Ralika", 0, 36)); // NOI18N

        fancyLabel20.setText("CREATED");
        fancyLabel20.setFont(new java.awt.Font("Magesta", 0, 20)); // NOI18N

        fancyImage6.setCornerRadius(0);
        fancyImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-properties-48.png"))); // NOI18N

        javax.swing.GroupLayout fancyPanel18Layout = new javax.swing.GroupLayout(fancyPanel18);
        fancyPanel18.setLayout(fancyPanel18Layout);
        fancyPanel18Layout.setHorizontalGroup(
            fancyPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fancyImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(fancyPanel18Layout.createSequentialGroup()
                .addGroup(fancyPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel18Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(fancyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel18Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(fancyLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel18Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(fancyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        fancyPanel18Layout.setVerticalGroup(
            fancyPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel18Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(fancyImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fancyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout fancyPanel12Layout = new javax.swing.GroupLayout(fancyPanel12);
        fancyPanel12.setLayout(fancyPanel12Layout);
        fancyPanel12Layout.setHorizontalGroup(
            fancyPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel12Layout.createSequentialGroup()
                .addComponent(fancyPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        fancyPanel12Layout.setVerticalGroup(
            fancyPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel12Layout.createSequentialGroup()
                .addComponent(fancyPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(fancyPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 160, 190));

        fancyPanel13.setGradientEnabled(false);
        fancyPanel13.setSolidBackgroundColor(new java.awt.Color(243, 243, 243));
        fancyPanel13.setSolidBackgroundEnabled(true);

        fancyPanel19.setBorderEnabled(true);
        fancyPanel19.setGradientEnabled(false);
        fancyPanel19.setSolidBackgroundColor(new java.awt.Color(255, 255, 255));
        fancyPanel19.setSolidBackgroundEnabled(true);

        fancyLabel21.setText("PENDING");
        fancyLabel21.setFont(new java.awt.Font("Magesta", 0, 20)); // NOI18N

        fancyLabel22.setText("8");
        fancyLabel22.setFont(new java.awt.Font("Ralika", 0, 36)); // NOI18N

        fancyLabel23.setText("REVIEW");
        fancyLabel23.setFont(new java.awt.Font("Magesta", 0, 20)); // NOI18N

        fancyImage5.setCornerRadius(0);
        fancyImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-data-pending-48.png"))); // NOI18N

        javax.swing.GroupLayout fancyPanel19Layout = new javax.swing.GroupLayout(fancyPanel19);
        fancyPanel19.setLayout(fancyPanel19Layout);
        fancyPanel19Layout.setHorizontalGroup(
            fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel19Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel19Layout.createSequentialGroup()
                        .addComponent(fancyImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel19Layout.createSequentialGroup()
                        .addGroup(fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fancyLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fancyLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fancyPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fancyLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        fancyPanel19Layout.setVerticalGroup(
            fancyPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel19Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(fancyImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fancyLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout fancyPanel13Layout = new javax.swing.GroupLayout(fancyPanel13);
        fancyPanel13.setLayout(fancyPanel13Layout);
        fancyPanel13Layout.setHorizontalGroup(
            fancyPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel13Layout.createSequentialGroup()
                .addComponent(fancyPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fancyPanel13Layout.setVerticalGroup(
            fancyPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel13Layout.createSequentialGroup()
                .addComponent(fancyPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(fancyPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 160, 190));

        fancyPanel2.setBorderColor(new java.awt.Color(194, 194, 194));
        fancyPanel2.setCornerRadius(9);
        fancyPanel2.setGradientEnabled(false);
        fancyPanel2.setGradientEnd(new java.awt.Color(228, 212, 238));
        fancyPanel2.setGradientStart(new java.awt.Color(203, 187, 238));
        fancyPanel2.setSolidBackgroundColor(new java.awt.Color(241, 241, 241));
        fancyPanel2.setSolidBackgroundEnabled(true);

        javax.swing.GroupLayout fancyPanel2Layout = new javax.swing.GroupLayout(fancyPanel2);
        fancyPanel2.setLayout(fancyPanel2Layout);
        fancyPanel2Layout.setHorizontalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        fancyPanel2Layout.setVerticalGroup(
            fancyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(fancyPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 200, 50));

        fancyPanel3.setBorderColor(new java.awt.Color(194, 194, 194));
        fancyPanel3.setCornerRadius(9);
        fancyPanel3.setGradientEnabled(false);
        fancyPanel3.setGradientEnd(new java.awt.Color(228, 212, 238));
        fancyPanel3.setGradientStart(new java.awt.Color(203, 187, 238));
        fancyPanel3.setSolidBackgroundColor(new java.awt.Color(241, 241, 241));
        fancyPanel3.setSolidBackgroundEnabled(true);

        javax.swing.GroupLayout fancyPanel3Layout = new javax.swing.GroupLayout(fancyPanel3);
        fancyPanel3.setLayout(fancyPanel3Layout);
        fancyPanel3Layout.setHorizontalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        fancyPanel3Layout.setVerticalGroup(
            fancyPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(fancyPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fancyButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton7ActionPerformed

    private void fancyButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton8ActionPerformed

    private void fancyButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton13ActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
    int choice = JOptionPane.showConfirmDialog(this, "Are you sure to logout?" ,"Confirm logout", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new LogInn().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogOutActionPerformed

    private void fancyButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton11ActionPerformed

    private void fancyButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardTeachert().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton LogOut;
    private fancyui.FancyButton fancyButton10;
    private fancyui.FancyButton fancyButton11;
    private fancyui.FancyButton fancyButton12;
    private fancyui.FancyButton fancyButton13;
    private fancyui.FancyButton fancyButton14;
    private fancyui.FancyButton fancyButton15;
    private fancyui.FancyButton fancyButton7;
    private fancyui.FancyButton fancyButton8;
    private fancyui.FancyImage fancyImage1;
    private fancyui.FancyImage fancyImage2;
    private fancyui.FancyImage fancyImage5;
    private fancyui.FancyImage fancyImage6;
    private fancyui.FancyImage fancyImage7;
    private fancyui.FancyLabel fancyLabel12;
    private fancyui.FancyLabel fancyLabel14;
    private fancyui.FancyLabel fancyLabel15;
    private fancyui.FancyLabel fancyLabel18;
    private fancyui.FancyLabel fancyLabel19;
    private fancyui.FancyLabel fancyLabel2;
    private fancyui.FancyLabel fancyLabel20;
    private fancyui.FancyLabel fancyLabel21;
    private fancyui.FancyLabel fancyLabel22;
    private fancyui.FancyLabel fancyLabel23;
    private fancyui.FancyPanel fancyPanel1;
    private fancyui.FancyPanel fancyPanel10;
    private fancyui.FancyPanel fancyPanel12;
    private fancyui.FancyPanel fancyPanel13;
    private fancyui.FancyPanel fancyPanel16;
    private fancyui.FancyPanel fancyPanel18;
    private fancyui.FancyPanel fancyPanel19;
    private fancyui.FancyPanel fancyPanel2;
    private fancyui.FancyPanel fancyPanel3;
    private fancyui.FancyPanel fancyPanel4;
    private fancyui.FancyTable fancyTable1;
    private fancyui.FancyTable fancyTable2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
