
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lyza
 */
public class LogInn extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogInn.class.getName());

    /**
     * Creates new form LogInn
     */
    public LogInn() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        fancyLabel1 = new fancyui.FancyLabel();
        jLabel5 = new javax.swing.JLabel();
        fancyImage2 = new fancyui.FancyImage();
        fancyPanel1 = new fancyui.FancyPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userfield = new fancyui.FancyTextField();
        passfield = new fancyui.FancyPasswordField();
        loginbtn = new fancyui.FancyButton();
        jLabel1 = new javax.swing.JLabel();
        createAccnt = new fancyui.FancyButton();
        fancyImage3 = new fancyui.FancyImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fancyLabel1.setForeground(new java.awt.Color(245, 197, 66));
        fancyLabel1.setText("LUMINEX");
        fancyLabel1.setFont(new java.awt.Font("Super Bouncer", 0, 29)); // NOI18N
        jPanel1.add(fancyLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Winter Poppins", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 17, 63));
        jLabel5.setText("Challenge You Mind, Light Up your knowledge");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 280, 30));

        fancyImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/774148120_1731905104754691_9160798377654078668_n.png"))); // NOI18N
        fancyImage2.setScaleType(fancyui.FancyImage.ScaleType.FIT);
        fancyImage2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fancyImage2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(fancyImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 370, 230));

        fancyPanel1.setBorderColor(new java.awt.Color(255, 255, 255));
        fancyPanel1.setBorderEnabled(true);
        fancyPanel1.setBorderThickness(1.75F);
        fancyPanel1.setBottomLeftRadius(20);
        fancyPanel1.setBottomRightRadius(20);
        fancyPanel1.setCornerRadius(20);
        fancyPanel1.setGradientEnd(new java.awt.Color(255, 255, 255));
        fancyPanel1.setGradientStart(new java.awt.Color(148, 51, 196));
        fancyPanel1.setOpacity(0.6F);
        fancyPanel1.setSolidBackgroundEnabled(true);

        jLabel2.setFont(new java.awt.Font("Winter Poppins", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 17, 63));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-test-account-24.png"))); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Winter Poppins", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 17, 63));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-password-30.png"))); // NOI18N
        jLabel4.setText("Password");

        userfield.setBackgroundColor(new java.awt.Color(204, 204, 249));
        userfield.setBorderEnabled(false);
        userfield.setBorderStyle(null);
        userfield.setCornerRadius(7);
        userfield.setFocusBorderColor(java.awt.Color.white);
        userfield.setPlaceholder("Username");
        userfield.setPlaceholderColor(new java.awt.Color(0, 0, 0));
        userfield.addActionListener(this::userfieldActionPerformed);

        passfield.setBackgroundColor(new java.awt.Color(204, 204, 249));
        passfield.setBorderEnabled(false);
        passfield.setCornerRadius(7);
        passfield.setPlaceholderColor(new java.awt.Color(0, 0, 0));

        loginbtn.setText("Login");
        loginbtn.setBackgroundColor(new java.awt.Color(204, 204, 249));
        loginbtn.setBorderEnabled(false);
        loginbtn.setBottomLeftRadius(7);
        loginbtn.setBottomRightRadius(7);
        loginbtn.setCornerRadius(7);
        loginbtn.setGradientAngle(180);
        loginbtn.setGradientEnd(new java.awt.Color(204, 204, 249));
        loginbtn.setHoverBackground(new java.awt.Color(191, 162, 255));
        loginbtn.addActionListener(this::loginbtnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Super Bouncer", 0, 36)); // NOI18N
        jLabel1.setText("Welcome Back");

        createAccnt.setText("Create Account?");
        createAccnt.setBackgroundColor(new java.awt.Color(204, 204, 249));
        createAccnt.setBorderEnabled(false);
        createAccnt.setCornerRadius(7);
        createAccnt.setHoverBackground(new java.awt.Color(191, 162, 255));
        createAccnt.addActionListener(this::createAccntActionPerformed);

        javax.swing.GroupLayout fancyPanel1Layout = new javax.swing.GroupLayout(fancyPanel1);
        fancyPanel1.setLayout(fancyPanel1Layout);
        fancyPanel1Layout.setHorizontalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel3))
                            .addGroup(fancyPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(userfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(createAccnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        fancyPanel1Layout.setVerticalGroup(
            fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fancyPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fancyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3))
                    .addGroup(fancyPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createAccnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(659, 659, 659))
        );

        userfield.getAccessibleContext().setAccessibleName("");
        userfield.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(fancyPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 320, 420));

        fancyImage3.setBorderColor(new java.awt.Color(255, 255, 255));
        fancyImage3.setBorderEnabled(true);
        fancyImage3.setBorderThickness(0.0F);
        fancyImage3.setCornerRadius(0);
        fancyImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dola (2).png"))); // NOI18N
        jPanel1.add(fancyImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        new DBConn().connect();
        String Username = userfield.getText();
        String Password = passfield.getText();

        String role = new DBConn().LogInn(Username, Password);

        if (role.equalsIgnoreCase("admin")) {
            JOptionPane.showMessageDialog(this, "Welcome Back Admin!");
            new Admin().setVisible(true);
            this.dispose();
        } else if (role.equalsIgnoreCase("Teacher")) {
            JOptionPane.showMessageDialog(this, "Hello, Teacher!");
            new DashboardTeachert().setVisible(true);
            this.dispose();
        } else if (role.equalsIgnoreCase("Student")) {
            JOptionPane.showMessageDialog(this, "Hello, Student"); //papalitan yung student ng name nila mismo kapag naglog in kung baga naidentify ng system kung sino ang naglog in
            new Dashboard().setVisible(true);
            this.dispose();
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Try Again!", "Login Failed!...", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                new LogInn().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void createAccntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccntActionPerformed

        int choice = JOptionPane.showConfirmDialog(this, "You don't have an Account?", "Confirm Create Account", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new CreateAccount().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_createAccntActionPerformed

    private void fancyImage2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fancyImage2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_fancyImage2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogInn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fancyui.FancyButton createAccnt;
    private fancyui.FancyImage fancyImage2;
    private fancyui.FancyImage fancyImage3;
    private fancyui.FancyLabel fancyLabel1;
    private fancyui.FancyPanel fancyPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private fancyui.FancyButton loginbtn;
    private fancyui.FancyPasswordField passfield;
    private fancyui.FancyTextField userfield;
    // End of variables declaration//GEN-END:variables
}
